# Generated by Django 3.1.6 on 2021-10-02 03:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('est_time', models.FloatField()),
                ('notes', models.CharField(max_length=1000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(verbose_name=datetime.datetime(2021, 10, 2, 3, 37, 11, 938708, tzinfo=utc))),
                ('archive', models.BooleanField()),
                ('requires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.requirement')),
            ],
        ),
    ]
